# Generated by Django 6.0.5 on 2026-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoValidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amid', models.BigIntegerField()),
                ('fec_descarga', models.DateTimeField(blank=True, null=True)),
                ('fec_estado', models.DateTimeField(blank=True, null=True)),
                ('busid', models.IntegerField(blank=True, null=True)),
                ('op', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('td01', models.IntegerField(blank=True, null=True)),
                ('td04', models.IntegerField(blank=True, null=True)),
                ('tabla', models.IntegerField(blank=True, null=True)),
                ('ver_tabla', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('is_contiene_bateria', models.BooleanField(blank=True, null=True)),
                ('is_contiene_gps', models.BooleanField(blank=True, null=True)),
                ('is_contiene_tiempo_vida', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_bateria', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_gps', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_tiempo_vida', models.BooleanField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('porcentaje_bateria', models.IntegerField(blank=True, null=True)),
                ('tiempo_vida', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['amid'], name='dashboard_e_amid_237a2d_idx'), models.Index(fields=['fecha_hora'], name='dashboard_e_fecha_h_14cc9a_idx'), models.Index(fields=['porcentaje_bateria'], name='dashboard_e_porcent_76b33c_idx')],
            },
        ),
    ]
