# Generated by Django 6.0.5 on 2026-05-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('CSV', 'CSV'), ('ORACLE', 'Oracle')], max_length=20)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('filas_obtenidas', models.IntegerField(default=0)),
                ('filas_creadas', models.IntegerField(default=0)),
                ('filas_eliminadas', models.IntegerField(default=0)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
