# Generated by Django 6.0.5 on 2026-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_logimportacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoValidadorLimpio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amid', models.BigIntegerField()),
                ('fec_descarga', models.DateTimeField(blank=True, null=True)),
                ('fec_estado', models.DateTimeField(blank=True, null=True)),
                ('busid', models.IntegerField(blank=True, null=True)),
                ('op', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('td01', models.IntegerField(blank=True, null=True)),
                ('td04', models.IntegerField(blank=True, null=True)),
                ('tabla', models.IntegerField(blank=True, null=True)),
                ('ver_tabla', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('is_contiene_bateria', models.BooleanField(blank=True, null=True)),
                ('is_contiene_gps', models.BooleanField(blank=True, null=True)),
                ('is_contiene_tiempo_vida', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_bateria', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_gps', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_tiempo_vida', models.BooleanField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('porcentaje_bateria', models.IntegerField(blank=True, null=True)),
                ('tiempo_vida', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('coordenadas_validas', models.BooleanField(default=False)),
                ('bateria_valida', models.BooleanField(default=False)),
                ('gps_valido', models.BooleanField(default=False)),
                ('tiene_error', models.BooleanField(default=False)),
                ('estado_bateria', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_gps', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_general', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_importacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_limpieza', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['amid'], name='dashboard_e_amid_53fcc3_idx'), models.Index(fields=['fecha_hora'], name='dashboard_e_fecha_h_f6e468_idx'), models.Index(fields=['porcentaje_bateria'], name='dashboard_e_porcent_93f263_idx'), models.Index(fields=['estado_general'], name='dashboard_e_estado__20839b_idx')],
                'constraints': [models.UniqueConstraint(fields=('amid', 'fecha_hora'), name='unique_limpio_amid_fecha_hora')],
            },
        ),
        migrations.CreateModel(
            name='EstadoValidadorRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amid', models.BigIntegerField()),
                ('fec_descarga', models.DateTimeField(blank=True, null=True)),
                ('fec_estado', models.DateTimeField(blank=True, null=True)),
                ('busid', models.IntegerField(blank=True, null=True)),
                ('op', models.IntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('patente', models.CharField(blank=True, max_length=50, null=True)),
                ('td01', models.IntegerField(blank=True, null=True)),
                ('td04', models.IntegerField(blank=True, null=True)),
                ('tabla', models.IntegerField(blank=True, null=True)),
                ('ver_tabla', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('is_contiene_bateria', models.BooleanField(blank=True, null=True)),
                ('is_contiene_gps', models.BooleanField(blank=True, null=True)),
                ('is_contiene_tiempo_vida', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_bateria', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_gps', models.BooleanField(blank=True, null=True)),
                ('is_error_obtener_tiempo_vida', models.BooleanField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('porcentaje_bateria', models.IntegerField(blank=True, null=True)),
                ('tiempo_vida', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['amid'], name='dashboard_e_amid_8f3cfd_idx'), models.Index(fields=['fecha_hora'], name='dashboard_e_fecha_h_a98163_idx'), models.Index(fields=['porcentaje_bateria'], name='dashboard_e_porcent_a69ee5_idx')],
                'constraints': [models.UniqueConstraint(fields=('amid', 'fecha_hora'), name='unique_raw_amid_fecha_hora')],
            },
        ),
    ]
