# Generated by Django 6.0.5 on 2026-06-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_estadovalidadorlimpio_estadovalidadorraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logimportacion',
            name='origen',
            field=models.CharField(choices=[('CSV', 'CSV'), ('ORACLE', 'Oracle'), ('LIMPIEZA', 'Limpieza')], max_length=20),
        ),
    ]
