# Generated by Django 6.0.5 on 2026-06-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_logimportacion_origen'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='estadovalidadorlimpio',
            name='dashboard_e_estado__20839b_idx',
        ),
        migrations.RemoveField(
            model_name='estadovalidadorlimpio',
            name='bateria_valida',
        ),
        migrations.RemoveField(
            model_name='estadovalidadorlimpio',
            name='coordenadas_validas',
        ),
        migrations.RemoveField(
            model_name='estadovalidadorlimpio',
            name='estado_bateria',
        ),
        migrations.RemoveField(
            model_name='estadovalidadorlimpio',
            name='estado_general',
        ),
        migrations.RemoveField(
            model_name='estadovalidadorlimpio',
            name='estado_gps',
        ),
        migrations.RemoveField(
            model_name='estadovalidadorlimpio',
            name='gps_valido',
        ),
        migrations.RemoveField(
            model_name='estadovalidadorlimpio',
            name='tiene_error',
        ),
    ]
