# Generated by Django 6.0.5 on 2026-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_estadovalidadorlimpio_dashboard_e_estado__20839b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionEsperadaValidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amid', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('serie_validador', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud_esperada', models.FloatField(blank=True, null=True)),
                ('longitud_esperada', models.FloatField(blank=True, null=True)),
                ('radio_metros', models.FloatField(blank=True, null=True)),
                ('operativa', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ubicación esperada de validador',
                'verbose_name_plural': 'Ubicaciones esperadas de validadores',
            },
        ),
    ]
