# Generated by Django 6.0.5 on 2026-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_ubicacionesperadavalidador'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUbicacionEsperadaValidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amid', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('serie_validador', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud_esperada', models.FloatField(blank=True, null=True)),
                ('longitud_esperada', models.FloatField(blank=True, null=True)),
                ('radio_metros', models.FloatField(blank=True, null=True)),
                ('operativa', models.BooleanField(default=True)),
                ('origen_ubicacion', models.CharField(default='excel', help_text='Origen de la ubicación: excel, laboratorio o laboratorio_default.', max_length=30)),
                ('fecha_inicio_vigencia', models.DateTimeField()),
                ('fecha_fin_vigencia', models.DateTimeField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField()),
                ('archivo_origen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Historial de ubicación esperada',
                'verbose_name_plural': 'Historial de ubicaciones esperadas',
                'indexes': [models.Index(fields=['amid'], name='dashboard_h_amid_49ba37_idx'), models.Index(fields=['fecha_inicio_vigencia'], name='dashboard_h_fecha_i_d0def1_idx'), models.Index(fields=['fecha_fin_vigencia'], name='dashboard_h_fecha_f_ce5b6b_idx'), models.Index(fields=['amid', 'fecha_inicio_vigencia', 'fecha_fin_vigencia'], name='dashboard_h_amid_84392a_idx')],
            },
        ),
    ]
