# Generated by Django 6.0.5 on 2026-06-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_historialubicacionesperadavalidador'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estadovalidadorlimpio',
            index=models.Index(fields=['amid', 'fecha_hora'], name='dashboard_e_amid_e28d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='estadovalidadorlimpio',
            index=models.Index(fields=['fecha_hora', 'latitud', 'longitud'], name='dashboard_e_fecha_h_f847df_idx'),
        ),
        migrations.AddIndex(
            model_name='estadovalidadorlimpio',
            index=models.Index(fields=['fecha_hora', 'porcentaje_bateria'], name='dashboard_e_fecha_h_107af4_idx'),
        ),
        migrations.AddIndex(
            model_name='estadovalidadorraw',
            index=models.Index(fields=['amid', 'fecha_hora'], name='dashboard_e_amid_8ebf21_idx'),
        ),
        migrations.AddIndex(
            model_name='estadovalidadorraw',
            index=models.Index(fields=['fecha_hora', 'latitud', 'longitud'], name='dashboard_e_fecha_h_bb917c_idx'),
        ),
        migrations.AddIndex(
            model_name='estadovalidadorraw',
            index=models.Index(fields=['fecha_hora', 'porcentaje_bateria'], name='dashboard_e_fecha_h_1b1b1c_idx'),
        ),
    ]
