# Generated by Django 6.0.5 on 2026-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_estadovalidadorlimpio_dashboard_e_amid_e28d3f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusZP',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('amid', models.BigIntegerField(db_column='AMID')),
                ('fec_descarga', models.DateTimeField(blank=True, db_column='FEC_DESCARGA', null=True)),
                ('fec_estado', models.DateTimeField(blank=True, db_column='FEC_ESTADO', null=True)),
                ('busid', models.IntegerField(blank=True, db_column='BUSID', null=True)),
                ('op', models.IntegerField(blank=True, db_column='OP', null=True)),
                ('version', models.CharField(blank=True, db_column='VERSION', max_length=50, null=True)),
                ('patente', models.CharField(blank=True, db_column='PATENTE', max_length=50, null=True)),
                ('td01', models.IntegerField(blank=True, db_column='TD01', null=True)),
                ('td04', models.IntegerField(blank=True, db_column='TD04', null=True)),
                ('tabla', models.IntegerField(blank=True, db_column='TABLA', null=True)),
                ('ver_tabla', models.CharField(blank=True, db_column='VER_TABLA', max_length=50, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, db_column='FECHA_HORA', null=True)),
                ('is_contiene_bateria', models.BooleanField(blank=True, db_column='IS_CONTIENE_BATERIA', null=True)),
                ('is_contiene_gps', models.BooleanField(blank=True, db_column='IS_CONTIENE_GPS', null=True)),
                ('is_contiene_tiempo_vida', models.BooleanField(blank=True, db_column='IS_CONTIENE_TIEMPO_VIDA', null=True)),
                ('is_error_obtener_bateria', models.BooleanField(blank=True, db_column='IS_ERROR_OBTENER_BATERIA', null=True)),
                ('is_error_obtener_gps', models.BooleanField(blank=True, db_column='IS_ERROR_OBTENER_GPS', null=True)),
                ('is_error_obtener_tiempo_vida', models.BooleanField(blank=True, db_column='IS_ERROR_OBTENER_TIEMPO_VIDA', null=True)),
                ('latitud', models.DecimalField(blank=True, db_column='LATITUD', decimal_places=10, max_digits=20, null=True)),
                ('longitud', models.DecimalField(blank=True, db_column='LONGITUD', decimal_places=10, max_digits=20, null=True)),
                ('porcentaje_bateria', models.IntegerField(blank=True, db_column='PORCENTAJE_BATERIA', null=True)),
                ('tiempo_vida', models.DateTimeField(blank=True, db_column='TIEMPO_VIDA', null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, db_column='FECHA_REGISTRO', null=True)),
            ],
            options={
                'db_table': 'VW_ESTATUS_ZP_DJANGO',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='logimportacion',
            options={'verbose_name': 'Log de importación', 'verbose_name_plural': 'Logs de importación'},
        ),
        migrations.AlterField(
            model_name='logimportacion',
            name='estado',
            field=models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error'), ('ADVERTENCIA', 'Advertencia'), ('INFO', 'Información')], help_text='Resultado del proceso.', max_length=20),
        ),
        migrations.AlterField(
            model_name='logimportacion',
            name='origen',
            field=models.CharField(choices=[('PROBAR_ORACLE', 'Probar conexión Oracle'), ('UBICACIONES_ORACLE', 'Ubicaciones esperadas Oracle'), ('BATERIA_BLOQUES_ORACLE', 'Batería bloques Oracle'), ('ESTADO_ORACLE', 'Estado general Oracle'), ('EXPORT_EXCEL', 'Exportación Excel'), ('SCHEDULER', 'Scheduler'), ('SISTEMA', 'Sistema'), ('CSV', 'CSV'), ('ORACLE', 'Oracle antiguo'), ('LIMPIEZA', 'Limpieza antigua'), ('EXCEL_UBICACIONES', 'Excel ubicaciones antiguo')], help_text='Proceso que generó el log.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='logimportacion',
            index=models.Index(fields=['origen'], name='dashboard_l_origen_cb1d60_idx'),
        ),
        migrations.AddIndex(
            model_name='logimportacion',
            index=models.Index(fields=['estado'], name='dashboard_l_estado_8f4914_idx'),
        ),
        migrations.AddIndex(
            model_name='logimportacion',
            index=models.Index(fields=['fecha_inicio'], name='dashboard_l_fecha_i_8c1b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='logimportacion',
            index=models.Index(fields=['origen', 'fecha_inicio'], name='dashboard_l_origen_0073c7_idx'),
        ),
    ]
