# Generated by Django 6.0.5 on 2026-08-12 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_retira_modelos_sqlite_antiguos_solo_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAmidExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amid', models.BigIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_amids_excluidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AMID excluido del panel de alertas',
                'verbose_name_plural': 'AMID excluidos del panel de alertas',
                'ordering': ['amid'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'amid'), name='uq_alerta_usuario_amid')],
            },
        ),
        migrations.CreateModel(
            name='AlertaUbicacionExcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ubicaciones_excluidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicaci\u00f3n excluida del panel de alertas',
                'verbose_name_plural': 'Ubicaciones excluidas del panel de alertas',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nombre'), name='uq_alerta_usuario_ubicacion')],
            },
        ),
    ]
