# Generated by Django 6.0.5 on 2026-09-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alertaamidexcluido_alertaubicacionexcluida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstatusZP',
        ),
    ]
