# Generated by Django 5.2 on 2026-10-05

import apps.dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0012_delete_estatuszp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrabajoArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(max_length=80),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESANDO", "Procesando"),
                            ("LISTO", "Listo"),
                            ("ERROR", "Error"),
                            ("EXPIRADO", "Expirado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "parametros_json",
                    models.JSONField(default=dict),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("progreso", models.PositiveSmallIntegerField(default=0)),
                ("mensaje", models.TextField(blank=True, default="")),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.dashboard.models.trabajo_archivo_upload_to,
                    ),
                ),
                ("nombre_archivo", models.CharField(blank=True, default="", max_length=255)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("leido", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trabajos_archivo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo de archivo",
                "verbose_name_plural": "Trabajos de archivo",
                "ordering": ["-fecha_solicitud"],
                "indexes": [
                    models.Index(fields=["estado", "fecha_solicitud"], name="dashboard_t_estado_691952_idx"),
                    models.Index(fields=["usuario", "leido", "fecha_solicitud"], name="dashboard_t_usuario_4ef6f6_idx"),
                    models.Index(fields=["fecha_expiracion"], name="dashboard_t_fecha_e_faefce_idx"),
                ],
            },
        ),
    ]
