# Generated by Django 6.0.5 on 2026-10-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.JSONField()),
            ],
            options={
                'db_table': 'xl_alignment',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.JSONField()),
            ],
            options={
                'db_table': 'xl_border',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='Dxf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.JSONField()),
            ],
            options={
                'db_table': 'xl_dxf',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.JSONField()),
            ],
            options={
                'db_table': 'xl_fill',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.JSONField()),
            ],
            options={
                'db_table': 'xl_font',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='NumberFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.JSONField()),
            ],
            options={
                'db_table': 'xl_number_format',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('data_json', models.JSONField()),
            ],
            options={
                'db_table': 'xl_protection',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Oculta'), ('VERY_HIDDEN', 'Muy oculta')], default='VISIBLE', max_length=16)),
                ('tab_color_json', models.JSONField(blank=True, null=True)),
                ('default_row_height', models.FloatField(blank=True, null=True)),
                ('default_col_width', models.FloatField(blank=True, null=True)),
                ('sheet_view_json', models.JSONField(blank=True, null=True)),
                ('page_setup_json', models.JSONField(blank=True, null=True)),
                ('margins_json', models.JSONField(blank=True, null=True)),
                ('print_json', models.JSONField(blank=True, null=True)),
                ('header_footer_json', models.JSONField(blank=True, null=True)),
                ('extra_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hoja de plantilla',
                'verbose_name_plural': 'Hojas de plantilla',
                'db_table': 'xl_sheet',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('export_filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla Excel',
                'verbose_name_plural': 'Plantillas Excel',
                'db_table': 'xl_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('source_filename', models.CharField(max_length=255)),
                ('source_ext', models.CharField(default='.xlsx', max_length=10)),
                ('source_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='excel_templates.template')),
            ],
            options={
                'verbose_name': 'Version de plantilla Excel',
                'verbose_name_plural': 'Versiones de plantilla Excel',
                'db_table': 'xl_template_version',
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='PrintTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.CharField(blank=True, default='', max_length=64)),
                ('cols', models.CharField(blank=True, default='', max_length=64)),
                ('extra_json', models.JSONField(blank=True, null=True)),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_title', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_print_title',
            },
        ),
        migrations.CreateModel(
            name='ImageRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_json', models.JSONField(blank=True, null=True)),
                ('media_name', models.CharField(blank=True, default='', max_length=255)),
                ('media_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('media_ext', models.CharField(blank=True, default='', max_length=16)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_image_ref',
            },
        ),
        migrations.CreateModel(
            name='DataValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqref_json', models.JSONField()),
                ('type', models.CharField(blank=True, default='', max_length=32)),
                ('formula1_json', models.JSONField(blank=True, null=True)),
                ('formula2_json', models.JSONField(blank=True, null=True)),
                ('options_json', models.JSONField(blank=True, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_validations', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_data_validation',
            },
        ),
        migrations.CreateModel(
            name='ConditionalFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqref_json', models.JSONField()),
                ('type', models.CharField(max_length=32)),
                ('operator', models.CharField(blank=True, default='', max_length=32)),
                ('priority', models.IntegerField(default=1)),
                ('stop_if_true', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, default='')),
                ('time_period', models.CharField(blank=True, default='', max_length=16)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('percent', models.BooleanField(blank=True, null=True)),
                ('bottom', models.BooleanField(blank=True, null=True)),
                ('std_dev', models.IntegerField(blank=True, null=True)),
                ('above_average', models.BooleanField(blank=True, null=True)),
                ('equal_average', models.BooleanField(blank=True, null=True)),
                ('formulas_json', models.JSONField(blank=True, null=True)),
                ('color_scale_json', models.JSONField(blank=True, null=True)),
                ('data_bar_json', models.JSONField(blank=True, null=True)),
                ('icon_set_json', models.JSONField(blank=True, null=True)),
                ('dxf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_templates.dxf')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_formats', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_conditional_format',
                'ordering': ['sheet_id', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Autofilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, default='', max_length=64)),
                ('columns_json', models.JSONField(blank=True, null=True)),
                ('sort_state_json', models.JSONField(blank=True, null=True)),
                ('hidden_rows_json', models.JSONField(blank=True, null=True)),
                ('sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autofilter', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_autofilter',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='excel_templates.alignment')),
                ('border', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='excel_templates.border')),
                ('fill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='excel_templates.fill')),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='excel_templates.font')),
                ('number_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='excel_templates.numberformat')),
                ('protection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='excel_templates.protection')),
            ],
            options={
                'db_table': 'xl_style',
                'ordering': ['hash'],
            },
        ),
        migrations.CreateModel(
            name='WorkbookMeta',
            fields=[
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='excel_templates.templateversion')),
                ('theme_xml', models.TextField(blank=True, default='')),
                ('defined_names_json', models.JSONField(blank=True, null=True)),
                ('workbook_props_json', models.JSONField(blank=True, null=True)),
                ('calc_props_json', models.JSONField(blank=True, null=True)),
                ('extra_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Metadatos del libro',
                'verbose_name_plural': 'Metadatos de libros',
                'db_table': 'xl_workbook_meta',
            },
        ),
        migrations.AddField(
            model_name='sheet',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='excel_templates.templateversion'),
        ),
        migrations.CreateModel(
            name='MergedRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_merged_range',
                'ordering': ['ref'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'ref'), name='uq_xl_merged_ref')],
            },
        ),
        migrations.CreateModel(
            name='CommentShell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_ref', models.CharField(max_length=16)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('from_col', models.PositiveIntegerField(blank=True, null=True)),
                ('from_row', models.PositiveIntegerField(blank=True, null=True)),
                ('from_col_off', models.IntegerField(blank=True, null=True)),
                ('from_row_off', models.IntegerField(blank=True, null=True)),
                ('to_col', models.PositiveIntegerField(blank=True, null=True)),
                ('to_row', models.PositiveIntegerField(blank=True, null=True)),
                ('to_col_off', models.IntegerField(blank=True, null=True)),
                ('to_row_off', models.IntegerField(blank=True, null=True)),
                ('text_json', models.TextField(blank=True, default='')),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_comment_shell',
                'ordering': ['cell_ref'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'cell_ref'), name='uq_xl_comment_celda')],
            },
        ),
        migrations.CreateModel(
            name='CellLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_idx', models.PositiveIntegerField()),
                ('col_idx', models.PositiveIntegerField()),
                ('value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(default='s', max_length=16)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_cell_label',
                'ordering': ['sheet_id', 'row_idx', 'col_idx'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'row_idx', 'col_idx'), name='uq_xl_label_celda')],
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_idx', models.PositiveIntegerField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('outline_level', models.PositiveIntegerField(default=0)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='excel_templates.sheet')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_templates.style')),
            ],
            options={
                'db_table': 'xl_row',
                'ordering': ['row_idx'],
                'indexes': [models.Index(fields=['sheet', 'row_idx'], name='ix_xl_row_sheet_indice')],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'row_idx'), name='uq_xl_row_sheet_indice')],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_idx', models.PositiveIntegerField()),
                ('max_idx', models.PositiveIntegerField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('best_fit', models.BooleanField(default=False)),
                ('outline_level', models.PositiveIntegerField(default=0)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='excel_templates.sheet')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_templates.style')),
            ],
            options={
                'db_table': 'xl_column',
                'ordering': ['min_idx', 'max_idx'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'min_idx', 'max_idx'), name='uq_xl_column_rango')],
            },
        ),
        migrations.CreateModel(
            name='CellStyleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_idx', models.PositiveIntegerField()),
                ('col_start', models.PositiveIntegerField()),
                ('col_end', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('HEADER', 'Cabecera'), ('LEGEND', 'Leyenda'), ('DATA', 'Dato'), ('UNKNOWN', 'Desconocido')], default='DATA', max_length=16)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_runs', to='excel_templates.sheet')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excel_templates.style')),
            ],
            options={
                'db_table': 'xl_cell_style_run',
                'ordering': ['sheet_id', 'row_idx', 'col_start'],
                'indexes': [models.Index(fields=['sheet', 'row_idx'], name='ix_xl_run_sheet_fila')],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('ref', models.CharField(blank=True, default='', max_length=64)),
                ('table_json', models.JSONField(blank=True, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='excel_templates.sheet')),
            ],
            options={
                'db_table': 'xl_table',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('sheet', 'name'), name='uq_xl_table_nombre')],
            },
        ),
        migrations.AddIndex(
            model_name='templateversion',
            index=models.Index(fields=['template', '-version_no'], name='ix_xl_version_template'),
        ),
        migrations.AddIndex(
            model_name='templateversion',
            index=models.Index(fields=['source_sha256'], name='ix_xl_version_sha256'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_no'), name='uq_xl_version_template_numero'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(fields=('version', 'position'), name='uq_xl_sheet_version_posicion'),
        ),
    ]
