-- ETAPA 3 - AUDITORIA DE RENDIMIENTO ORACLE
-- Solo lectura: no contiene DDL, DML, COMMIT ni ejecucion de procedures.
-- Ejecutar como script completo en DBeaver y exportar los resultados.

-- 1. Version exacta de Oracle.
SELECT BANNER_FULL
FROM V$VERSION
WHERE BANNER_FULL IS NOT NULL
ORDER BY BANNER_FULL;

-- 2. Estadisticas del optimizador. STALE_STATS=YES o LAST_ANALYZED antiguo
-- puede explicar planes deficientes sin que falte ningun indice.
SELECT
    TABLE_NAME,
    NUM_ROWS,
    BLOCKS,
    AVG_ROW_LEN,
    SAMPLE_SIZE,
    LAST_ANALYZED,
    STALE_STATS
FROM USER_TAB_STATISTICS
WHERE OBJECT_TYPE = 'TABLE'
  AND TABLE_NAME IN (
      'ESTATUS_ZP',
      'BATERIA_BLOQUE_30MIN',
      'ALERTA_VALIDADOR_RESUMEN',
      'AMID_MAESTRO_ALERTAS',
      'ALERTA_REGLA_PARAM',
      'UBICACION_ESPERADA_VALIDADOR',
      'HISTORIAL_UBICACION_ESPERADA'
  )
ORDER BY TABLE_NAME;

-- 3. Indices completos y orden real de sus columnas.
SELECT
    i.TABLE_NAME,
    i.INDEX_NAME,
    i.UNIQUENESS,
    i.STATUS,
    i.VISIBILITY,
    i.BLEVEL,
    i.LEAF_BLOCKS,
    i.DISTINCT_KEYS,
    i.CLUSTERING_FACTOR,
    i.NUM_ROWS,
    i.LAST_ANALYZED,
    LISTAGG(
        c.COLUMN_NAME || ' ' || c.DESCEND,
        ', '
    ) WITHIN GROUP (ORDER BY c.COLUMN_POSITION) AS COLUMNAS
FROM USER_INDEXES i
JOIN USER_IND_COLUMNS c
  ON c.INDEX_NAME = i.INDEX_NAME
 AND c.TABLE_NAME = i.TABLE_NAME
WHERE i.TABLE_NAME IN (
    'ESTATUS_ZP',
    'BATERIA_BLOQUE_30MIN',
    'ALERTA_VALIDADOR_RESUMEN',
    'AMID_MAESTRO_ALERTAS',
    'ALERTA_REGLA_PARAM',
    'UBICACION_ESPERADA_VALIDADOR',
    'HISTORIAL_UBICACION_ESPERADA'
)
GROUP BY
    i.TABLE_NAME,
    i.INDEX_NAME,
    i.UNIQUENESS,
    i.STATUS,
    i.VISIBILITY,
    i.BLEVEL,
    i.LEAF_BLOCKS,
    i.DISTINCT_KEYS,
    i.CLUSTERING_FACTOR,
    i.NUM_ROWS,
    i.LAST_ANALYZED
ORDER BY i.TABLE_NAME, i.INDEX_NAME;

-- 4. Definicion exacta de la vista que convierte los textos de ESTATUS_ZP.
SELECT VIEW_NAME, TEXT_LENGTH, TEXT
FROM USER_VIEWS
WHERE VIEW_NAME IN (
    'VW_ESTATUS_ZP_DJANGO',
    'VW_ALERTA_VALIDADOR_ACTIVA'
)
ORDER BY VIEW_NAME;

-- 5. Cobertura de AMID activos y resumen. Deben coincidir.
SELECT
    (SELECT COUNT(*)
       FROM USR_LAB.AMID_MAESTRO_ALERTAS
      WHERE ACTIVO = 1) AS AMIDS_ACTIVOS,
    (SELECT COUNT(*)
       FROM USR_LAB.ALERTA_VALIDADOR_RESUMEN) AS RESUMENES_TOTALES,
    (SELECT COUNT(*)
       FROM USR_LAB.VW_ALERTA_VALIDADOR_ACTIVA) AS RESUMENES_ACTIVOS
FROM DUAL;

-- 6. Distribucion de alertas activas. Permite estimar la selectividad real.
SELECT
    NIVEL_ALERTA_GLOBAL,
    NIVEL_ALERTA_GPS,
    NIVEL_ALERTA_BATERIA,
    TIENE_ALERTA,
    COUNT(*) AS CANTIDAD
FROM USR_LAB.VW_ALERTA_VALIDADOR_ACTIVA
GROUP BY
    NIVEL_ALERTA_GLOBAL,
    NIVEL_ALERTA_GPS,
    NIVEL_ALERTA_BATERIA,
    TIENE_ALERTA
ORDER BY CANTIDAD DESC;

-- 7. Volumen por AMID de los bloques de bateria.
SELECT
    MIN(CANTIDAD) AS MIN_BLOQUES_POR_AMID,
    ROUND(AVG(CANTIDAD), 2) AS PROM_BLOQUES_POR_AMID,
    MAX(CANTIDAD) AS MAX_BLOQUES_POR_AMID,
    COUNT(*) AS AMIDS_CON_BLOQUES
FROM (
    SELECT AMID, COUNT(*) AS CANTIDAD
    FROM USR_LAB.BATERIA_BLOQUE_30MIN
    GROUP BY AMID
);

-- 8. Rango temporal y frescura de los bloques preparados.
SELECT
    MIN(FECHA_HORA_BLOQUE) AS PRIMER_BLOQUE,
    MAX(FECHA_HORA_BLOQUE) AS ULTIMO_BLOQUE,
    MAX(FECHA_ACTUALIZACION) AS ULTIMA_ACTUALIZACION,
    COUNT(DISTINCT AMID) AS AMIDS
FROM USR_LAB.BATERIA_BLOQUE_30MIN;

-- 9. Configuracion actual de jobs relacionados.
SELECT
    JOB_NAME,
    ENABLED,
    STATE,
    JOB_ACTION,
    REPEAT_INTERVAL,
    LAST_START_DATE,
    LAST_RUN_DURATION,
    NEXT_RUN_DATE,
    FAILURE_COUNT
FROM USER_SCHEDULER_JOBS
WHERE UPPER(JOB_NAME) LIKE '%ALERTA%'
   OR UPPER(JOB_NAME) LIKE '%BAT%'
ORDER BY JOB_NAME;

-- 10. Ultimas ejecuciones: duracion y errores reales.
SELECT *
FROM (
    SELECT
        JOB_NAME,
        STATUS,
        ACTUAL_START_DATE,
