-- Ejecutar despues de V009__detalle_caidas_bateria_fuente_unica.sql.
-- Cada consulta incluye el resultado esperado.

-- 1. Los tres objetos deben aparecer VALID.
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'ALERTA_BATERIA_CAIDA_EVENTO',
    'PRC_REFRESCAR_CAIDAS_BAT',
    'PRC_UPD_ALERTAS_VAL'
)
ORDER BY OBJECT_TYPE, OBJECT_NAME;

-- 2. No debe retornar filas.
SELECT NAME, TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME IN ('PRC_REFRESCAR_CAIDAS_BAT', 'PRC_UPD_ALERTAS_VAL')
ORDER BY NAME, SEQUENCE;

-- 3. Recalcula reglas, eventos y resumen dentro del flujo seguro existente.
BEGIN
    USR_LAB.PRC_RECALCULAR_ALERTAS_SEGURO;
END;
/

-- 4. Conteo informativo de eventos confirmados en la ventana de 14 dias.
SELECT
    COUNT(*) AS TOTAL_EVENTOS,
    COUNT(DISTINCT AMID) AS AMID_CON_CAIDAS,
    MIN(FECHA_CAIDA) AS PRIMERA_CAIDA,
    MAX(FECHA_CAIDA) AS ULTIMA_CAIDA,
    MAX(FECHA_CALCULO) AS FECHA_CALCULO
FROM USR_LAB.ALERTA_BATERIA_CAIDA_EVENTO;

-- 5. Debe retornar 0. CAIDAS_HIST ya incluye las caidas de hoy.
WITH detalle AS (
    SELECT
        AMID,
        COUNT(*) AS CAIDAS_HIST,
        SUM(CASE
            WHEN FECHA_CAIDA >= TRUNC(SYSDATE)
             AND FECHA_CAIDA < TRUNC(SYSDATE) + 1
            THEN 1 ELSE 0
        END) AS CAIDAS_HOY
    FROM USR_LAB.ALERTA_BATERIA_CAIDA_EVENTO
    GROUP BY AMID
)
SELECT COUNT(*) AS INCONSISTENCIAS
FROM USR_LAB.VW_ALERTA_VALIDADOR_ACTIVA r
LEFT JOIN detalle d ON d.AMID = r.AMID
WHERE NVL(r.CAIDAS_HIST, 0) <> NVL(d.CAIDAS_HIST, 0)
   OR NVL(r.CAIDAS_HOY, 0) <> NVL(d.CAIDAS_HOY, 0);

-- 6. Debe mostrar 0 en PRC_UPD y al menos 1 en PRC_REFRESCAR.
SELECT
    NAME,
    SUM(CASE
        WHEN UPPER(TEXT) LIKE '%BAT_CAIDA_MIN_DETECTAR%' THEN 1
        ELSE 0
    END) AS REFERENCIAS_REGLA_DETECCION
FROM USER_SOURCE
WHERE NAME IN ('PRC_REFRESCAR_CAIDAS_BAT', 'PRC_UPD_ALERTAS_VAL')
  AND TYPE = 'PROCEDURE'
GROUP BY NAME
ORDER BY NAME;

-- 7. Muestra eventos recientes para revision visual.
SELECT
    AMID,
    FECHA_CAIDA_DESDE,
    FECHA_CAIDA,
    BATERIA_DESDE,
    BATERIA_HASTA,
    CAIDA_DIF
FROM USR_LAB.ALERTA_BATERIA_CAIDA_EVENTO
ORDER BY FECHA_CAIDA DESC
FETCH FIRST 20 ROWS ONLY;
