-- Validacion de V011. Solo lectura; no modifica datos.

-- 1. Procedimiento valido.
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'PRC_SINC_UBIC_AMID';

-- 2. Errores de compilacion: debe devolver cero filas.
SELECT NAME, TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME = 'PRC_SINC_UBIC_AMID'
ORDER BY SEQUENCE;

-- 3. Job habilitado y proxima ejecucion a las 06:10.
SELECT JOB_NAME,
       ENABLED,
       STATE,
       JOB_TYPE,
       REPEAT_INTERVAL,
       LAST_START_DATE,
       NEXT_RUN_DATE,
       FAILURE_COUNT
FROM USER_SCHEDULER_JOBS
WHERE JOB_NAME = 'JOB_SINC_UBIC_AMID';

-- 4. AMID activos sin ubicacion vigente: debe dar 0.
SELECT COUNT(*) AS ACTIVOS_SIN_UBICACION
FROM USR_LAB.AMID_MAESTRO_ALERTAS m
WHERE m.ACTIVO = 1
  AND NOT EXISTS (
      SELECT 1
      FROM USR_LAB.UBICACION_ESPERADA_VALIDADOR u
      WHERE TRIM(u.AMID) = TRIM(CAST(m.AMID AS VARCHAR2(20)))
  );

-- 5. AMID activos con ubicacion, pero sin historial abierto: debe dar 0.
SELECT COUNT(*) AS ACTIVOS_SIN_HISTORIAL_ABIERTO
FROM USR_LAB.AMID_MAESTRO_ALERTAS m
JOIN USR_LAB.UBICACION_ESPERADA_VALIDADOR u
  ON TRIM(u.AMID) = TRIM(CAST(m.AMID AS VARCHAR2(20)))
WHERE m.ACTIVO = 1
  AND NOT EXISTS (
      SELECT 1
      FROM USR_LAB.HISTORIAL_UBICACION_ESPERADA h
      WHERE TRIM(h.AMID) = TRIM(u.AMID)
        AND h.FECHA_FIN_VIGENCIA IS NULL
  );

-- 6. No debe haber mas de un historial abierto por AMID.
SELECT AMID, COUNT(*) AS HISTORIALES_ABIERTOS
FROM USR_LAB.HISTORIAL_UBICACION_ESPERADA
WHERE FECHA_FIN_VIGENCIA IS NULL
GROUP BY AMID
HAVING COUNT(*) > 1
ORDER BY AMID;

-- 7. Comprobacion puntual de los AMID que motivaron el cambio.
SELECT m.AMID,
       m.ACTIVO,
       u.NOMBRE,
       u.LATITUD_ESPERADA,
       u.LONGITUD_ESPERADA,
       u.RADIO_METROS,
       u.VERSION_ZP,
       u.ARCHIVO_ORIGEN,
       h.ORIGEN_UBICACION,
       h.FECHA_INICIO_VIGENCIA,
       h.FECHA_FIN_VIGENCIA
FROM USR_LAB.AMID_MAESTRO_ALERTAS m
LEFT JOIN USR_LAB.UBICACION_ESPERADA_VALIDADOR u
  ON TRIM(u.AMID) = TRIM(CAST(m.AMID AS VARCHAR2(20)))
LEFT JOIN USR_LAB.HISTORIAL_UBICACION_ESPERADA h
  ON TRIM(h.AMID) = TRIM(CAST(m.AMID AS VARCHAR2(20)))
 AND h.FECHA_FIN_VIGENCIA IS NULL
WHERE TRIM(CAST(m.AMID AS VARCHAR2(20))) IN ('7501415', '7518977')
ORDER BY m.AMID;

-- 8. Ultimas ejecuciones automaticas/manuales registradas por Scheduler.
SELECT JOB_NAME,
       STATUS,
       ACTUAL_START_DATE,
       RUN_DURATION,
       ERROR#,
       ADDITIONAL_INFO
FROM USER_SCHEDULER_JOB_RUN_DETAILS
WHERE JOB_NAME = 'JOB_SINC_UBIC_AMID'
ORDER BY LOG_DATE DESC
FETCH FIRST 10 ROWS ONLY;
