-- BKL-002C - preflight exclusivamente READ ONLY, compatible con Oracle 11g.
-- No contiene DDL, DML ni invocaciones de procedures operativos.

SET LINESIZE 240
SET PAGESIZE 500

PROMPT === Version Oracle ===
SELECT PRODUCT, VERSION, STATUS
FROM PRODUCT_COMPONENT_VERSION
WHERE UPPER(PRODUCT) LIKE 'ORACLE DATABASE%';

PROMPT === Usuario actual ===
SELECT USER AS USUARIO_ACTUAL FROM DUAL;

PROMPT === Privilegios relevantes ===
SELECT PRIVILEGE
FROM SESSION_PRIVS
WHERE PRIVILEGE IN (
    'CREATE TABLE',
    'CREATE PROCEDURE',
    'CREATE JOB',
    'CREATE SEQUENCE',
    'CREATE TRIGGER',
    'MANAGE SCHEDULER',
    'CREATE ANY JOB'
)
ORDER BY PRIVILEGE;

PROMPT === Objetos BKL-002C preexistentes ===
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS, LAST_DDL_TIME
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'ALERTA_RECALCULO_CONTROL',
    'ALERTA_RECALCULO_CONTROL_AUD',
    'ALERTA_RECALCULO_SOLICITUD',
    'PKG_ALERTA_LEASE',
    'PRC_PROCESAR_RECALC_ALERTA'
)
ORDER BY OBJECT_NAME, OBJECT_TYPE;

PROMPT === Jobs BKL-002C preexistentes ===
SELECT JOB_NAME, ENABLED, STATE, JOB_ACTION, REPEAT_INTERVAL,
       AUTO_DROP, RESTARTABLE
FROM USER_SCHEDULER_JOBS
WHERE JOB_NAME IN (
    'JOB_PROCESAR_RECALC_ALERTAS',
    'JOB_LIMPIAR_HIST_UBICACION'
)
ORDER BY JOB_NAME;

PROMPT === Definicion vigente de JOB_UPD_ALERTAS_VAL ===
SELECT JOB_NAME, ENABLED, STATE, JOB_TYPE, JOB_ACTION, REPEAT_INTERVAL,
       LAST_START_DATE, LAST_RUN_DURATION, NEXT_RUN_DATE, FAILURE_COUNT
FROM USER_SCHEDULER_JOBS
WHERE JOB_NAME = 'JOB_UPD_ALERTAS_VAL';

PROMPT === Ejecuciones Scheduler actualmente activas ===
SELECT JOB_NAME, SESSION_ID, RUNNING_INSTANCE, ELAPSED_TIME, CPU_USED
FROM USER_SCHEDULER_RUNNING_JOBS
ORDER BY JOB_NAME;

PROMPT === Firmas de procedures relevantes ===
SELECT OBJECT_NAME, PACKAGE_NAME, OVERLOAD, POSITION, SEQUENCE,
       ARGUMENT_NAME, IN_OUT, DATA_TYPE, DEFAULTED
FROM USER_ARGUMENTS
WHERE OBJECT_NAME IN (
    'PRC_UPD_ALERTAS_VAL',
    'PRC_APLICAR_REGLAS_ALERTA',
    'PRC_RECALCULAR_ALERTAS_SEGURO',
    'PRC_RECLASIFICAR_ALERTAS',
    'PRC_REFRESCAR_CAIDAS_BAT',
    'PRC_VALIDAR_REGLAS_ALERTA',
    'PRC_LIMPIAR_HIST_UBICACION'
)
ORDER BY OBJECT_NAME, OVERLOAD, SEQUENCE;

PROMPT === Cantidad de lineas del fuente vigente ===
SELECT NAME, TYPE, COUNT(*) AS LINEAS, MIN(LINE) AS PRIMERA, MAX(LINE) AS ULTIMA
FROM USER_SOURCE
WHERE NAME IN ('PRC_UPD_ALERTAS_VAL', 'PRC_APLICAR_REGLAS_ALERTA')
GROUP BY NAME, TYPE
ORDER BY NAME;

