-- BKL-002C - tablas de control, auditoria y solicitudes manuales.
-- Requiere ejecutar antes 00_preflight_readonly.sql.
-- No usa secuencias ni triggers: los identificadores se generan con SYS_GUID().

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE USR_LAB.ALERTA_RECALCULO_CONTROL (
    RECURSO                VARCHAR2(64 CHAR)  NOT NULL,
    OWNER_TOKEN            VARCHAR2(32 CHAR),
    OWNER_TIPO             VARCHAR2(16 CHAR),
    OWNER_JOB_NAME         VARCHAR2(128 CHAR),
    OWNER_SESSION_ID       VARCHAR2(64 CHAR),
    OWNER_RUNNING_INSTANCE NUMBER,
    LEASE_VERSION          NUMBER(19) DEFAULT 0 NOT NULL,
    FECHA_ADQUISICION      TIMESTAMP(6) WITH TIME ZONE,
    FECHA_EXPIRACION       TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_ALERTA_RECALCULO_CONTROL PRIMARY KEY (RECURSO),
    CONSTRAINT CK_ARC_OWNER_TIPO CHECK (
        OWNER_TIPO IS NULL OR OWNER_TIPO IN ('SCHEDULER', 'DIRECT')
    ),
    CONSTRAINT CK_ARC_OWNER_COMPLETO CHECK (
        (OWNER_TOKEN IS NULL
         AND OWNER_TIPO IS NULL
         AND FECHA_ADQUISICION IS NULL
         AND FECHA_EXPIRACION IS NULL)
        OR
        (OWNER_TOKEN IS NOT NULL
         AND OWNER_TIPO IS NOT NULL
         AND FECHA_ADQUISICION IS NOT NULL
         AND FECHA_EXPIRACION IS NOT NULL)
    )
);

CREATE TABLE USR_LAB.ALERTA_RECALCULO_CONTROL_AUD (
    AUDIT_ID               VARCHAR2(32 CHAR) NOT NULL,
    RECURSO                VARCHAR2(64 CHAR) NOT NULL,
    EVENTO                 VARCHAR2(32 CHAR) NOT NULL,
    OWNER_TOKEN            VARCHAR2(32 CHAR),
    OWNER_TIPO             VARCHAR2(16 CHAR),
    OWNER_JOB_NAME         VARCHAR2(128 CHAR),
    OWNER_SESSION_ID       VARCHAR2(64 CHAR),
    OWNER_RUNNING_INSTANCE NUMBER,
    LEASE_VERSION          NUMBER(19),
    FECHA_EVENTO           TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    USUARIO_EVENTO         VARCHAR2(128 CHAR),
    MOTIVO                 VARCHAR2(1000 CHAR),
    EVIDENCIA              VARCHAR2(2000 CHAR),
    CONSTRAINT PK_ALERTA_RECALC_CTRL_AUD PRIMARY KEY (AUDIT_ID)
);

CREATE TABLE USR_LAB.ALERTA_RECALCULO_SOLICITUD (
    SOLICITUD_ID       VARCHAR2(32 CHAR) NOT NULL,
    ORIGEN             VARCHAR2(20 CHAR) NOT NULL,
    MODO               VARCHAR2(16 CHAR) NOT NULL,
    ESTADO             VARCHAR2(16 CHAR) NOT NULL,
    USUARIO_SOLICITANTE VARCHAR2(128 CHAR) NOT NULL,
    FECHA_SOLICITUD    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    FECHA_INICIO       TIMESTAMP(6) WITH TIME ZONE,
    FECHA_FIN          TIMESTAMP(6) WITH TIME ZONE,
    FECHA_ACTUALIZACION TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    INTENTOS           NUMBER(10) DEFAULT 0 NOT NULL,
    OWNER_TOKEN        VARCHAR2(32 CHAR),
    LEASE_VERSION      NUMBER(19),
    ERROR_CODIGO       NUMBER,
    ERROR_MENSAJE      VARCHAR2(2000 CHAR),
    CONSTRAINT PK_ALERTA_RECALC_SOL PRIMARY KEY (SOLICITUD_ID),
    CONSTRAINT CK_ARS_ORIGEN CHECK (ORIGEN IN ('DJANGO_PANEL', 'DBA_MANUAL')),
    CONSTRAINT CK_ARS_MODO CHECK (MODO IN ('RAPIDO', 'COMPLETO')),
    CONSTRAINT CK_ARS_ESTADO CHECK (
        ESTADO IN ('PENDIENTE', 'EJECUTANDO', 'OK', 'ERROR')
    ),
    CONSTRAINT CK_ARS_INTENTOS CHECK (INTENTOS >= 0)
);

CREATE INDEX USR_LAB.IX_ARS_ESTADO_FECHA
ON USR_LAB.ALERTA_RECALCULO_SOLICITUD (ESTADO, FECHA_SOLICITUD);

INSERT INTO USR_LAB.ALERTA_RECALCULO_CONTROL (
    RECURSO,
    LEASE_VERSION
) VALUES (
    'ALERTAS_RECALCULO',
    0
);

COMMIT;

PROMPT Tablas BKL-002C creadas. Los jobs siguen deshabilitados/no creados.

