-- BKL-002C - health checks READ ONLY, Oracle 11g.

SET LINESIZE 260
SET PAGESIZE 500

PROMPT === Objetos y compilacion ===
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS, LAST_DDL_TIME
FROM USER_OBJECTS
WHERE OBJECT_NAME IN (
    'ALERTA_RECALCULO_CONTROL',
    'ALERTA_RECALCULO_CONTROL_AUD',
    'ALERTA_RECALCULO_SOLICITUD',
    'PKG_ALERTA_LEASE',
    'PRC_PROCESAR_RECALC_ALERTA',
    'PRC_UPD_ALERTAS_VAL',
    'PRC_APLICAR_REGLAS_ALERTA'
)
ORDER BY OBJECT_NAME, OBJECT_TYPE;

SELECT NAME, TYPE, LINE, POSITION, TEXT
FROM USER_ERRORS
WHERE NAME IN (
    'PKG_ALERTA_LEASE',
    'PRC_PROCESAR_RECALC_ALERTA',
    'PRC_UPD_ALERTAS_VAL',
    'PRC_APLICAR_REGLAS_ALERTA'
)
ORDER BY NAME, TYPE, SEQUENCE;

PROMPT === Estado derivado del lease ===
SELECT RECURSO, OWNER_TOKEN, OWNER_TIPO, OWNER_JOB_NAME,
       OWNER_SESSION_ID, OWNER_RUNNING_INSTANCE, LEASE_VERSION,
       FECHA_ADQUISICION, FECHA_EXPIRACION,
       CASE
           WHEN OWNER_TOKEN IS NULL THEN 'LIBRE'
           WHEN FECHA_EXPIRACION > SYSTIMESTAMP THEN 'ACTIVO'
           ELSE 'SOSPECHOSO'
       END AS ESTADO_DERIVADO
FROM USR_LAB.ALERTA_RECALCULO_CONTROL
WHERE RECURSO = 'ALERTAS_RECALCULO';

PROMPT === Requests por estado ===
SELECT ESTADO, MODO, COUNT(*) AS CANTIDAD,
       MIN(FECHA_SOLICITUD) AS MAS_ANTIGUA,
       MAX(FECHA_ACTUALIZACION) AS ULTIMA_ACTUALIZACION
FROM USR_LAB.ALERTA_RECALCULO_SOLICITUD
GROUP BY ESTADO, MODO
ORDER BY ESTADO, MODO;

PROMPT === Ultimas 50 solicitudes ===
SELECT *
FROM (
    SELECT SOLICITUD_ID, ORIGEN, MODO, ESTADO, USUARIO_SOLICITANTE,
           FECHA_SOLICITUD, FECHA_INICIO, FECHA_FIN, INTENTOS,
           OWNER_TOKEN, LEASE_VERSION, ERROR_CODIGO, ERROR_MENSAJE
    FROM USR_LAB.ALERTA_RECALCULO_SOLICITUD
    ORDER BY FECHA_SOLICITUD DESC
)
WHERE ROWNUM <= 50;

PROMPT === Ultimos 50 eventos de lease ===
SELECT *
FROM (
    SELECT EVENTO, OWNER_TOKEN, OWNER_TIPO, OWNER_JOB_NAME,
           OWNER_SESSION_ID, OWNER_RUNNING_INSTANCE, LEASE_VERSION,
           FECHA_EVENTO, USUARIO_EVENTO, MOTIVO, EVIDENCIA
    FROM USR_LAB.ALERTA_RECALCULO_CONTROL_AUD
    ORDER BY FECHA_EVENTO DESC
)
WHERE ROWNUM <= 50;

PROMPT === Jobs relevantes; nuevos deben seguir disabled antes del cutover ===
SELECT JOB_NAME, ENABLED, STATE, JOB_ACTION, REPEAT_INTERVAL,
       LAST_START_DATE, LAST_RUN_DURATION, NEXT_RUN_DATE, FAILURE_COUNT
FROM USER_SCHEDULER_JOBS
WHERE JOB_NAME IN (
    'JOB_UPD_ALERTAS_VAL',
    'JOB_PROCESAR_RECALC_ALERTAS',
    'JOB_LIMPIAR_HIST_UBICACION'
)
ORDER BY JOB_NAME;

PROMPT === Jobs ejecutandose ahora ===
SELECT JOB_NAME, SESSION_ID, RUNNING_INSTANCE, ELAPSED_TIME, CPU_USED
FROM USER_SCHEDULER_RUNNING_JOBS
WHERE JOB_NAME IN (
    'JOB_UPD_ALERTAS_VAL',
    'JOB_PROCESAR_RECALC_ALERTAS',
    'JOB_LIMPIAR_HIST_UBICACION'
)
ORDER BY JOB_NAME;

PROMPT === Ultimas 30 ejecuciones relevantes ===
SELECT *
FROM (
    SELECT JOB_NAME, STATUS, ACTUAL_START_DATE, RUN_DURATION,
           ERROR#, ADDITIONAL_INFO
    FROM USER_SCHEDULER_JOB_RUN_DETAILS
    WHERE JOB_NAME IN (
        'JOB_UPD_ALERTAS_VAL',
        'JOB_PROCESAR_RECALC_ALERTAS',
        'JOB_LIMPIAR_HIST_UBICACION'
    )
    ORDER BY ACTUAL_START_DATE DESC
)
WHERE ROWNUM <= 30;

PROMPT === Evidencia de instrumentacion de procedures ===
SELECT NAME, LINE, TEXT
FROM USER_SOURCE
WHERE NAME IN ('PRC_UPD_ALERTAS_VAL', 'PRC_APLICAR_REGLAS_ALERTA')
  AND UPPER(TEXT) LIKE '%PKG_ALERTA_LEASE%'
ORDER BY NAME, LINE;

